# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from zk import ZK
import os
import sys

from PyQt5 import QtCore, QtGui, QtWidgets

from datetime import datetime


class Worker(QtCore.QThread):
    sinout = QtCore.pyqtSignal(str)

    def __init__(self, parent=None):
        super(Worker, self).__init__(parent)
        self.working = True
        self.num = 0

    def __del__(self):
        self.working = False
        self.wait()

    def run(self):
        try:
            for attendance in conn.live_capture():

                if attendance is None:
                    pass
                else:
                    user_data = str(attendance).split()
                    # Transmitting signal
                    self.sinout.emit(user_data[1])
                    # Thread hibernates for 2 seconds
                    self.sleep(2)

        except Exception as e:
            print("Process terminate : {}".format(e))
        finally:
            if conn:
                conn.disconnect()


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.thread = Worker()

        MainWindow.setObjectName("MainWindow")
        MainWindow.showFullScreen()
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.EmployeeData = QtWidgets.QGroupBox(self.centralwidget)
        self.EmployeeData.setGeometry(QtCore.QRect(30, 70, 301, 181))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.EmployeeData.setFont(font)
        self.EmployeeData.setObjectName("EmployeeData")
        self.emp_name_label = QtWidgets.QLabel(self.EmployeeData)
        self.emp_name_label.setGeometry(QtCore.QRect(10, 30, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.emp_name_label.setFont(font)
        self.emp_name_label.setObjectName("emp_name_label")
        self.emp_no_label = QtWidgets.QLabel(self.EmployeeData)
        self.emp_no_label.setGeometry(QtCore.QRect(10, 80, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.emp_no_label.setFont(font)
        self.emp_no_label.setObjectName("emp_no_label")
        self.date_label = QtWidgets.QLabel(self.EmployeeData)
        self.date_label.setGeometry(QtCore.QRect(10, 130, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.date_label.setFont(font)
        self.date_label.setObjectName("date_label")
        self.emp_name = QtWidgets.QLabel(self.EmployeeData)
        self.emp_name.setGeometry(QtCore.QRect(10, 50, 271, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.emp_name.setFont(font)
        self.emp_name.setText("")
        self.emp_name.setObjectName("emp_name")
        self.emp_no = QtWidgets.QLabel(self.EmployeeData)
        self.emp_no.setGeometry(QtCore.QRect(10, 100, 271, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.emp_no.setFont(font)
        self.emp_no.setText("")
        self.emp_no.setObjectName("emp_no")
        self.date = QtWidgets.QLabel(self.EmployeeData)
        self.date.setGeometry(QtCore.QRect(10, 150, 271, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.date.setFont(font)
        self.date.setText("")
        self.date.setObjectName("date")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(30, 260, 471, 201))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 467, 197))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        # Exit button
        self.exitBtn = QtWidgets.QPushButton(self.centralwidget)
        self.exitBtn.setGeometry(QtCore.QRect(30, 480, 471, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.exitBtn.setFont(font)
        self.exitBtn.setStyleSheet("background-color : rgb(255, 0, 0);\n"
                                   "color: rgb(255, 255, 255);\n"
                                   "\n"
                                   "")
        self.exitBtn.setObjectName("exitBtn")
        self.exitBtn.clicked.connect(self.close_system)
        # Reset button
        self.resetBtn = QtWidgets.QPushButton(self.centralwidget)
        self.resetBtn.setGeometry(QtCore.QRect(360, 220, 111, 31))
        self.resetBtn.setObjectName("resetBtn")
        self.resetBtn.clicked.connect(self.reset_system)

        self.listWidget = QtWidgets.QListWidget(self.scrollAreaWidgetContents)
        self.listWidget.setGeometry(QtCore.QRect(0, 0, 471, 200))
        self.listWidget.setObjectName("listWidget")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 788, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.thread.start()
        self.thread.sinout.connect(self.readFinger)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.EmployeeData.setTitle(_translate(
            "MainWindow", "Employee Details"))
        self.emp_name_label.setText(_translate("MainWindow", "Name"))
        self.emp_no_label.setText(_translate("MainWindow", "Employee No"))
        self.date_label.setText(_translate("MainWindow", "Date"))
        self.exitBtn.setText(_translate("MainWindow", "Exit"))
        self.resetBtn.setText(_translate("MainWindow", "Reset"))

    def close_system(self):
        sys.exit()

    def reset_system(self):
        self.emp_name.setText('')
        self.emp_no.setText('')
        self.date.setText('')

    def readFinger(self, user_id):
        print(user_id)
        today = datetime.today()
        for user in users:
            if user.user_id == user_id:
                print(user)
                self.emp_name.setText(user.name)
                self.emp_no.setText(user.user_id)
                time = today.strftime("%d/%m/%Y %H:%M:%S")
                self.date.setText(time)
                self.listWidget.addItem(
                    f"{time} - {user.user_id} - {user.name}")


if __name__ == "__main__":
    conn = None
    zk = ZK('172.21.0.8', port=4370)
    conn = zk.connect()
    users = conn.get_users()

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
